### ISSUE TITLE
[Fixed] Odyssey Moon Jingle issue with OMM:Rebirth

### ISSUE THREAD

**Issue by Shmelvin64** [eros71-dev/sm64ex-coop-mods#2]
While using OMM:Rebirth, collecting a star correctly plays the new jingle but the background music doesn't continue playing afterwards

**Comment by eros71-dev** [comment]
I'm still looking into this issue, although having to work with lua bytecode makes it harder to check what could be causing the issue, if I find the solution I'll post another update here, otherwise it is most likely impossible for me to solve.

**Comment by eros71-dev** [comment]
I might have found out why, the reason might be that to "workaround" an issue I had with the fanfare sequence looping all the time, I added a silent loop at the end. In vanilla sm64 you usually just leave the level and it is usually not noticeable, but because OMM makes you stay in the level, it seems like it just keeps playing that sequence instead, so it just keeps playing the silent loop, instead of fading back into the level music. I may have to change my mod to force it to play the original level music but it would start the song from the beggining instead of fading back from the last pause.

**Comment by eros71-dev** [comment]
Good news, I've just released a patch that fixes it!
